govau/content-guide

- _assets/scss/guide.scss
- _includes/header.liquid
Add the search box to the top of the home page for #4
> Add search box to the home page

- _includes/search.liquid
Removing the search extracts as requested in #4
> Remove display of search extracts in search results

- _about/index.md
- _accessibility-inclusivity/aboriginal-torres-strait-islander.md
- _accessibility-inclusivity/assistive-technologies.md
- _accessibility-inclusivity/audience-diversity.md
- _accessibility-inclusivity/images-alt-text.md
- _accessibility-inclusivity/inclusive-language-terms.md
- _accessibility-inclusivity/languages-other-than-english.md
- _accessibility-inclusivity/pdf-accessibility.md
- _accessibility-inclusivity/translation.md
- _accessibility-inclusivity/video-accessibility.md
- _content-types/documents.md
- _content-types/surveys.md
- _punctuation-grammar/em-dashes.md
- _punctuation-grammar/hyphens.md
- _sources/index.md
- _terms-phrases/dictionaries.md
Styles all remaining external links as external links.
> Converted remainder of external links

- CHANGELOG.md
- README.md
- _about/index.md
- _config.yml
- _content-types/surveys.md
- _sources/index.md
- index.md
> Renaming guide

- _accessibility-inclusivity/screen-readers.md
Add clarity about screen readers
Added note about front-loading info to assist skimming
> Added some extra explanation to Screen  Reader

- _assets/scss/guide.scss
- _layouts/homepage-draft.liquid
- _layouts/page.liquid
- _pages/collections/sources.html
- _sources/index.md
- index.md
This pulls in the latest work on the template. I'm pulling this into `develop` now so that the proofers experience closer to the final template (we can always switch it back to the old template in `index.md`).
> Merge Feature/home page

- CHANGELOG.md
- _accessibility-inclusivity/aboriginal-torres-strait-islander.md
- _accessibility-inclusivity/audience-diversity.md
- _accessibility-inclusivity/images-alt-text.md
- _accessibility-inclusivity/inclusive-language-terms.md
- _accessibility-inclusivity/screen-readers.md
- _accessibility-inclusivity/translation.md
- _accessibility-inclusivity/video-accessibility.md
- _content-structure/bullet-point-lists.md
- _content-structure/headings-subheadings.md
- _content-structure/hyperlinks.md
- _content-structure/plan-structure.md
- _how-to-use-guide/index.md
- _numbers-measurements/dates.md
- _numbers-measurements/numbers.md
- _numbers-measurements/temperature.md
- _punctuation-grammar/colons.md
- _punctuation-grammar/commas.md
- _punctuation-grammar/em-dashes.md
- _punctuation-grammar/gerunds.md
- _punctuation-grammar/semicolons.md
- _sources/index.md
- _terms-phrases/australian-government.md
- _terms-phrases/government-departments.md
- _types-of-content/forms.md
- _writing-style/audience.md
- _writing-style/tone.md
- _writing-style/voice.md
- index.md
Adds new guidance on punctuating lists and fixes guide examples accordingly.
> Guidance change/bullets

- _includes/header.liquid
- _includes/search.liquid
Signed-off-by: Dominik Wilkowski <Hi@Dominik-Wilkowski.com>
> fixed search action path

- _includes/search.liquid
- _pages/privacy.md
- _writing-style/plain-english.md
Have updated privacy statement to apply to subdomain.
Fixed 2 small typos.
> Add Google Analytics 

- README.md
Also removed link to incorrect (DTO) crest.
> Update README.md to reflect release

- _accessibility-inclusivity/wcag.md
> Fix WCAG typo

- _pages/404.md
* Screenshots
* Notes
Workflow TBC
> added 404 markdown

- nginx.conf
* Screenshots
* Notes
Workflow TBC
> added nginx.conf

- CHANGELOG.md
- _content-structure/headings-subheadings.md
- _pages/404.md
- _pages/collections/content-types.html
- _punctuation-grammar/capitalisation.md
- _punctuation-grammar/full-stops.md
- _terms-phrases/states-territories.md
- _types-of-content/documents.md
- _types-of-content/pdfs.md
- index.md
- nginx.conf
When we are ready to properly PR `develop` to `master` there may be conflicts, but I couldn't find another way to progress with current situation (content that still needs to be tested on staging).
> Update master with selected commits from `develop`

- _search-engines/writing-for-the-user.md
> Fixed quotation mark for writing for the user

- _search-engines/how-people-search.md
> Spacing fix for how people search

- _search-engines/identifying-and-placing-keywords
> add link to identifying and placing keywords

- _search-engines/identifying-and-placing-keywords
- _search-engines/using-headings
> wording change to using headings

- _search-engines/defining-your-metadata
- _search-engines/identifying-and-placing-keywords
> use of cms in defining your metadata

- _search-engines/creating-effective-meta-titles-and-descriptions
- _search-engines/identifying-and-placing-keywords
> cms spell out in creating effective meta titles

- _terms-phrases/abbreviations.md
Content guide edits from Google doc (https://docs.google.com/document/d/1mnkOQCR-FhziM3-bWFRYJogjjzUBVGgzCbZu9YBT4cA/edit?ts=59c1ac45#)
> Update abbreviations info

- _pages/collections/search-engines.html
> Added missing word  to statement

- _writing-style/readability.md
Hi @gazanson looked good. I just made it a bit more prominent and added the specific WCAG rec.
> Readability advice

- _numbers-measurements/numbers.md
As per https://github.com/govau/content-guide/pull/226/
> Add abbreviation of thousands

- _accessibility-inclusivity/wcag.md
WAFFLE PB#178: There is no SC 1.1.5
Change to 1.4.5
> Correct WCAG criteria 1.4.5

- _accessibility-inclusivity/wcag.md
Use of master as suggested to PR this
> Changed WCAG criteria 1.1.5 to 1.4.5

- _pages/collections/search-engines.html
- _search-engines/keywords.md
- _search-engines/on-page-optimisation.md
- _search-engines/quick-seo-checklist.md
Includes all changes from Libby, Jools and Steve
> Seo version3

- _includes/head.liquid
- bin/cibuild.sh
- bin/cideploy.sh
- robots-production.txt
- robots.txt
* Adds a robots file and meta tag to stop the staging site being indexed by search engines
> added robots.txt file

- .circleci/config.yml
- CHANGELOG.md
- README.md
> 1.3.1 updates

- CHANGELOG.md
- _accessibility-inclusivity/aboriginal-torres-strait-islander.md
- _accessibility-inclusivity/inclusive-language-terms.md
- _accessibility-inclusivity/languages-other-than-english.md
- _content-structure/hyperlinks.md
- _content-structure/mobile-first.md
- _content-structure/navigation-labels.md
- _layouts/homepage-draft.liquid
- _pages/how-to-use.md
- _pages/sources.md
- _terms-phrases/digital-terms.md
- _types-of-content/forms.md
* Screenshots
* Notes
Workflow TBC
> Fix broken links.

- _pages/how-to-use.md
* Screenshots
* Notes
Workflow TBC
> Bugfix how guidance

- _accessibility-inclusivity/languages-other-than-english.md
* Screenshots
* Notes
Workflow TBC
> Remove redundant link

- _accessibility-inclusivity/audience-diversity.md
Thanks for the commit @davidjb merging this to our `develop` branch now. Cheers.
> Use inclusive language in Audience Diversity

- .gitignore
- CHANGELOG.md
- Dockerfile
- README.md
- _config.yml
- _pages/how-to-use.md
Docker image for local development
Fix broken link
> Add Docker image and fix broken link

- _accessibility-inclusivity/aboriginal-torres-strait-islander.md
- _accessibility-inclusivity/inclusive-language-terms.md
- _accessibility-inclusivity/pdf-accessibility.md
- _accessibility-inclusivity/video-accessibility.md
- _pages/sources.md
- _punctuation-grammar/em-dashes.md
- _types-of-content/tables.md
* Use HTTPS links where possible
> Use HTTPS links where possible

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- Gemfile
- Gemfile.lock
- _accessibility-inclusivity/inclusive-language-terms.md
- _terms-phrases/acronyms.md
- index.md
- manifest-production.yml
- manifest-staging.yml
- manifest-testing.yml
* Screenshots
* Notes
Workflow TBC
> Pushing to dev inclusivity and acronyms 

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- Gemfile
- Gemfile.lock
- _accessibility-inclusivity/inclusive-language-terms.md
- _terms-phrases/acronyms.md
- index.md
- manifest-production.yml
- manifest-staging.yml
- manifest-testing.yml
* Screenshots
* Notes
Workflow TBC
> Develop update date and inclusivity and acronyms  

- index.md
* Screenshots
* Notes
Workflow TBC
> Update how to join the Content COP
